version: 0.2

env:
  variables:
    AWS_REGION: "ca-central-1"
    TEMPLATE_FILE: "ec2.yaml"

phases:
  install:
    commands:
      - echo "Installing AWS CLI..."
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo "Validating CloudFormation template..."
      - aws cloudformation validate-template --region $AWS_REGION --template-body file://$TEMPLATE_FILE

  build:
    commands:
      - echo "Deploying CloudFormation stack..."
      - aws cloudformation deploy \
          --region $AWS_REGION \
          --template-file $TEMPLATE_FILE \
          --stack-name ec2-stack \
          --capabilities CAPABILITY_NAMED_IAM

  post_build:
    commands:
      - echo "Build completed successfully at $(date +"%Y-%m-%d %H:%M:%S %Z")"
