version: 0.2

env:
  variables:
    AWS_REGION: "ca-central-1"
    TEMPLATE_FILE: "ec2.yaml"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "=== INSTALL PHASE START ==="
      - echo "Removing any conflicting AWS CLI versions..."
      - sudo rm -f /usr/local/bin/aws || true
      - sudo rm -f /usr/bin/aws || true
      - echo "Installing AWS CLI v2..."
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip -q awscliv2.zip
      - sudo ./aws/install --update
      - aws --version
      - echo "=== INSTALL PHASE END ==="

  pre_build:
    commands:
      - echo "=== PRE_BUILD PHASE START ==="
      - aws cloudformation validate-template --region $AWS_REGION --template-body file://$TEMPLATE_FILE
      - echo "=== PRE_BUILD PHASE END ==="

  build:
    commands:
      - echo "=== BUILD PHASE START ==="
      - aws cloudformation deploy \
          --region $AWS_REGION \
          --template-file $TEMPLATE_FILE \
          --stack-name ec2-stack \
          --capabilities CAPABILITY_NAMED_IAM
      - echo "=== BUILD PHASE END ==="

  post_build:
    commands:
      - echo "=== POST_BUILD PHASE START ==="
      - echo "Build completed successfully at $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
      - echo "=== POST_BUILD PHASE END ==="
