version: 0.2

env:
  variables:
    AWS_REGION: "ca-central-1"
    TEMPLATE_FILE: "ec2.yaml"
    STACK_NAME: "ec2-stack"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "=== INSTALL PHASE START ==="
      - echo "Installing AWS CLI v2..."
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip -q awscliv2.zip
      - sudo ./aws/install --update
      - aws --version
      - echo "=== INSTALL PHASE END ==="

  pre_build:
    commands:
      - echo "=== PRE_BUILD PHASE START ==="
      - aws cloudformation validate-template --region $AWS_REGION --template-body file://$TEMPLATE_FILE
      - echo "=== PRE_BUILD PHASE END ==="

  build:
    commands:
      - echo "=== BUILD PHASE START ==="
      # ✅ use YAML block literal syntax for clarity
      - |
        aws cloudformation deploy \
          --region "$AWS_REGION" \
          --template-file "$TEMPLATE_FILE" \
          --stack-name "$STACK_NAME" \
          --parameter-overrides \
            ParameterKey=EC2AMIID,ParameterValue=ami-03814457ed908d8f6 \
            ParameterKey=EC2KeyPairName,ParameterValue=andrew-keypair \
            ParameterKey=EC2InstanceType,ParameterValue=t2.micro \
            ParameterKey=SubnetID,ParameterValue=subnet-0d4cc4dcd1ae2b192 \
            ParameterKey=SecurityGroupID,ParameterValue=sg-0de74e2ea3383ef00 \
          --capabilities CAPABILITY_NAMED_IAM
      - echo "=== BUILD PHASE END ==="

  post_build:
    commands:
      - echo "=== POST_BUILD PHASE START ==="
      - echo "Build completed successfully at $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
      - echo "=== POST_BUILD PHASE END ==="
