AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy an EC2 instance in an existing VPC/Subnet

Parameters:
  EC2AMIID:
    Type: String
    Description: AMI ID to use for the EC2 instance
  EC2KeyPairName:
    Type: String
    Description: Existing EC2 Key Pair name
  EC2InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type
  SubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID where the instance will be launched
  SecurityGroupID:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group ID to attach to the instance

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref EC2AMIID
      KeyName: !Ref EC2KeyPairName
      InstanceType: !Ref EC2InstanceType
      SubnetId: !Ref SubnetID
      SecurityGroupIds:
        - !Ref SecurityGroupID
      Tags:
        - Key: Name
          Value: CodeBuild-EC2-Instance

Outputs:
  InstanceId:
    Description: The ID of the newly created EC2 instance
    Value: !Ref EC2Instance
  InstancePublicIP:
    Description: The Public IP of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
